### ISSUE TITLE
几个问题，建议

### ISSUE THREAD

**Issue by cancundeyingzi** [lnstow/KeepApp#2]
第一个退出和停止有啥区别？
第二个每次开机之后都要来点一遍吗？
第三个 发现软件被杀死之后再自动打开。

**Comment by lnstow** [comment]
首先，这个软件已经不再维护了，所以你说的这些问题，可能无法及时改进和修复
其次，这个软件是很久之前写的了，有些代码我也记不清了，所以只能大概回答一下
1. 退出会关闭本应用，停止就是暂停，直到点开始才继续
2. 是每次这个应用重新打开就要点开始按钮（做不到自启动，只是大概率保后台）
3. 没咋看明白，是本应用还是被保护的应用？

另外长按退出按钮可以切换debug模式，不过我忘了有啥用😅

**Comment by cancundeyingzi** [comment]
> 首先，这个软件已经不再维护了，所以你说的这些问题，可能无法及时改进和修复 其次，这个软件是很久之前写的了，有些代码我也记不清了，所以只能大概回答一下
> 
> 1. 退出会关闭本应用，停止就是暂停，直到点开始才继续
> 2. 是每次这个应用重新打开就要点开始按钮（做不到自启动，只是大概率保后台）
> 3. 没咋看明白，是本应用还是被保护的应用？
> 
> 另外长按退出按钮可以切换debug模式，不过我忘了有啥用😅

谢了
